#!/usr/bin/ruby

# 1から20までの数をプリントするプログラム。
# ただし3の倍数のときは数の代わりに｢Fizz｣と、5の倍数のときは｢Buzz｣とプリントし、3と5両方の倍数の場合には｢FizzBuzz｣とプリントする。

(1..20).each do |number|
    case
    when number % 3 == 0 && number % 5 == 0 # 3と5両方の倍数の場合には｢FizzBuzz｣とプリントする。
        puts "FizzBuzz"
    when number % 3 == 0 # 3の倍数のときは数の代わりに｢Fizz｣とプリントする。
        puts "Fizz"
    when number % 5 == 0 # 5の倍数のときは｢Buzz｣とプリントする。
        puts "Buzz"
    else
        puts number # 上記以外の場合は数をそのままプリントする。
    end
end
