#!/usr/bin/ruby
# frozen_string_literal: true

ALL_PINS_DOWN = 10

shots = ARGV[0].split(',').map do |shot|
  if shot == 'X'
    [ALL_PINS_DOWN, 0]
  else
    shot.to_i
  end
end

frames = shots.flatten.each_slice(2).to_a

if frames[9][0] == ALL_PINS_DOWN || frames[9].sum == ALL_PINS_DOWN
  frames[9] += frames[10]
  frames.delete_at 10
  if frames[9][2] == ALL_PINS_DOWN
    frames[9] += frames[10]
    frames.delete_at 10
  end
end

point = 0
frames.each_with_index do |frame, i|
  point += if i == 9
             frame.sum
           elsif frame[0] == ALL_PINS_DOWN
             if i == 8 && frames[i + 1][0] == ALL_PINS_DOWN
               frame[0] + frames[i + 1][0] + frames[i + 1][2]
             elsif frames[i + 1][0] == ALL_PINS_DOWN
               frame[0] + frames[i + 1][0] + frames[i + 2][0]
             else
               frame[0] + frames[i + 1][0] + frames[i + 1][1]
             end
           elsif frame.sum == ALL_PINS_DOWN
             frame.sum + frames[i + 1][0]
           else
             frame.sum
           end
end
puts point
