#!/usr/bin/ruby
# frozen_string_literal: true

score = ARGV[0]
scores = score.split(',')
shots = []
scores.each do |s|
  if s == 'X' # strike
    shots << 10
    shots << 0
  else
    shots << s.to_i
  end
end

frames = []
shots.each_slice(2) do |s|
  frames << s
end

# 10フレーム目を3投する場合
if frames[9][0] == 10 || frames[9].sum == 10
  frames[9] += frames[10]
  frames.delete_at 10
  if frames[9][2] == 10
    frames[9] += frames[10]
    frames.delete_at 10
  end
end

point = 0
frames.each_with_index do |frame, i|
  point += if i == 9 # 最終フレームの場合
             frame.sum
           elsif frame[0] == 10 # strike
             if i == 8 # 第9フレーム
               if frames[i + 1][0] == 10 # 最終フレーム１投目がstrike
                 frame[0] + frames[i + 1][0] + frames[i + 1][2]
               else
                 frame[0] + frames[i + 1][0] + frames[i + 1][1]
               end
             elsif frames[i + 1][0] == 10 # 次のフレームの１投目がstrike
               frame[0] + frames[i + 1][0] + frames[i + 2][0]
             else
               frame[0] + frames[i + 1][0] + frames[i + 1][1]
             end
           elsif frame.sum == 10 # spare
             frame.sum + frames[i + 1][0]
           else
             frame.sum
           end
end
puts point
